### ISSUE TITLE
3.minutes not running rake tasks

### ISSUE THREAD

**Issue by 5hanth** [Ebbe/arask#18]
https://github.com/Ebbe/arask/blob/fe7d8944eaac0ed1f59afc91aa1a6c9caca12f1a/lib/arask/setup.rb#L55

this is probably not allowing `interval: 3.minutes` to work.
and following is not creating any task in db.

`
  arask.create task: "ticker:complete_my_task", interval: 3.minutes
`

edit: seems like it works on local. but on AWS ECS it never puts a record in db.

**Comment by Ebbe** [comment]
```
irb(main):004:0> 3.minutes.to_s.to_i
=> 180
```

It just converts it to seconds.

Seems like you could be having a db problem. Try putting a `puts "Setting up arask"` as the very first line in the initializer to see if it is actually run, and check the log output from rails to see if any errors occurs.
There shouldn't be any difference running it on localhost and aws.

**Comment by 5hanth** [comment]
@Ebbe issue was the way I start puma. `bundle exec puma -e production` fails to start initializers. while `bundle exec rails s -u puma -e production`  starts initializers.

now ActiveJob is processing jobs using default :async adaptor. Although rake task is running only for first time when server is started with `run_first_time` option. will keep this thread updated once I figure out what's stopping arask to run the task.

**Comment by Ebbe** [comment]
It is because of this: https://github.com/Ebbe/arask/blob/master/lib/arask.rb#L12

I made a check to see if rails started as a server, so it wouldn't run when running other rails commands. But apparently this is not so simple.. https://stackoverflow.com/questions/12088025/detect-if-application-was-started-as-http-server-or-not-rake-task-rconsole-etc/12246652#12246652

A simple `defined?(::Puma)` could fix it for Puma, but there should be a better solution. 

Right now you can start the server with `bundle exec rails server -e production` (it already uses puma)

**Comment by Ebbe** [comment]
Please test with the new version of arask: 1.2.4
